### ISSUE TITLE
bug: Failed on Windows 10

### ISSUE THREAD

**Issue by DanIverson** [JessiBaughman/OpenVnmrJ_WSL#4] opened 2024-09-13 00:48 UTC
I tried on Windows 10. The attached install_summary is the output. I removed stuff about installing packages etc. I then read step 4 of the installation instructions to install VcXsrc, which I did. I then tried again. Another failure. Output in install_again. Note the xhost failures trying to open the display.

[install_summary.txt](https://github.com/user-attachments/files/16987059/install_summary.txt)

[install_again.txt](https://github.com/user-attachments/files/16987067/install_again.txt)

**Comment by DanIverson** [comment] 2024-09-13 04:37
I tried to run xterm. It did not start. If I do
  export DISPLAY=:0.0
then xterm works.
After doing the export DISPLAY=:0.0, then running load.nmr showed the installer window. After clicking "Install", the progress window did not appear, but the installation proceeded. By checking with "ps -ef" commands, I could tell when the installation completed. After killing the installation java process, load.nmr continued asking about installing walkup/service accounts, adding fidlib, etc. Running vnmrj then worked and I was able to rt fid1d and process the data.

**Comment by DanIverson** [comment] 2024-09-13 16:36
Turns out the progress monitor "appears" but it is located off the screen, so one does not see it. Also, OVJ and OVJ admin
windows come up with a reasonable height but their width is about 5 times too wide. Not sure if there is some WSLg option that controls this stuff.

**Comment by JessiBaughman** [comment] 2024-09-14 14:15
VcXsrc might need a firewall rule (it's supposed to prompt on install). If you have an updated version of Windows 10 (21H2+), you can use WSLg, which doesn't use all the Xauthority stuff that VcXsrc uses to try to avoid those issues. I'm thinking maybe I should just take the VcXsrv option out. It's more error prone than what it's probably worth at this point. I'll push out the updated readme that clarifies VcXsrv is for W10 20H1-21H2.

Both VcXsrv and WSLg are prone to windows opening off screen, though I've had this issue much less with WSLg. That's more of a long-persistent, ironic Windows OS issue; poor windows management allowing windows to appear off screen. There are some workarounds mentioned  in the [WSLg Issue #332](https://github.com/microsoft/wslg/issues/332). Usually (not always), once you get a window on screen and close it, the next time it appears it will be at least mostly on screen and then clicking an edge (as if to resize) will bring it all the way on screen.

In your current Ubuntu 20.04 distro, is root your default account? Selecting to use a current distro assumes that you have a user account set as default and that it matches the one you enter in the initial panel. It also said in the initial install that vnmr1 already existed. Was this being installed in a distribution that already had OpenVnmrJ installed? It's not intended for upgrading, so maybe I'll add that clarification to the Readme and add a check in the script. If you already have OpenVnmrJ, it's best to just run the upgrade script from the installer. This script is intended for fresh installs of OpenVnmrJ.

**Comment by DanIverson** [comment] 2024-09-14 16:23
I had tried wsl about a year ago. It installed OVJ but I was never able to get the graphics to work. I also tried cygwin, mingw, xming, and other stuff, so this PC may have conflicting pieces. Its current level is 22H2.
I unregistered the Ubuntu distros and did wsl --uninstall. I ran wsl and it complained it needed a kernel update so I figured that that is where your tool starts its work. I got the following output:

Updating WSL
Checking for updates.
The most recent version of Windows Subsystem for Linux is already installed.
Invalid distribution name: '--no-launch'.
To get a list of valid distributions, use 'wsl.exe --list --online'.
Error code: Wsl/InstallDistro/WSL_E_DISTRO_NOT_FOUND
Starting WSL install
.exe : The term '.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ .exe install --root
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by DanIverson** [comment] 2024-09-14 18:32
I copied your installer to owsl and added the line
  Set-PSDebug -trace 2
at the top of the file. Attached is the debug output. I also ran wsl -l, which is where I think things go south.
[debug.txt](https://github.com/user-attachments/files/17003434/debug.txt)

**Comment by JessiBaughman** [comment] 2024-09-15 02:25
It seems this time it didn't set the variable for chosen distribution. Did it not prompt for one?

At this point, I think I'd recommend trying to "reset" your system as this is getting really obscure. So ```wsl --unregister <distro>``` for the <distro> you plan to use if needed. Then find it in the Start menu, and if still there, right-click and select uninstall. In PowerShell, manually run ```wsl --update```, followed by ```wsl -l``` to see that it looks fine. Then maybe try the script again. After clicking ok, make sure you select a distro at the PowerShell prompt, otherwise abort.

I'll finish the Readme update and push it shortly so you can follow along with the updated step-by-step.

**Comment by DanIverson** [comment] 2024-09-16 00:06
I have been playing a bit more with WSL. When I ran the script, I was not prompted for a distribution. I made a small change to your script that fixes that problem. It comments out an "if" conditional. Generally, things are working. I get a lot of Locator errors during OVJ installation,so I added a feature that avoids starting the Locator during installation. By doing  touch LocatorOff in the dvdimageOVJ directory, load.nmr will not try to start it. I made both of these changes to your script, which is attached. I made a new dvdimage zip file which has the changes in OVJ to fix the selinux problem, fixes the installer progress monitor from appearing off-screen, and now  recognizes a LocatorOff file in the dvdimageOVJ directory as a sign to not start the Locator. You can download this dvdimage zip file at: https://www.dropbox.com/scl/fi/agm74jhxrz0b8oi7n9e88/ovj32_ddr_jb.zip?rlkey=ixc8tzwqfkq9fmqq9u9hlk79b&st=0dlx6i47&dl=0

OVJ shortcut on desktop starts OVJ with the last OS (eg U24) that I installed. If I start a WSL from the Start menu in order to start OVJ manually, it starts the "Default" OS, which in my case is U22. Perhaps your script should do a "wsl -s $installDist" to select it as the default. I did not make that change to your script.

Your script works pretty well. I tried it with U22, U24, and Alma9. All worked.
[ovjwsl.zip](https://github.com/user-attachments/files/17007812/ovjwsl.zip)

**Comment by JessiBaughman** [comment] 2024-09-16 04:49
Thanks for looking into this. I was fighting getting the cups-pdf install via script to work the past few days. That If statement wasn't supposed to span that whole region, but since it's unnecessary, I took it out. I added the LocatorOff feature (Krish will like that) and added a prompt to ask if the user wants to set the chosen distribution to the WSL default. (e15617cf866691259c5b8f3d0daef28d8349db81)

I tested out the linked installer with the changes and had no install issues with any of the distros. However, after wsl restarts, the window opens small like below for both Ubuntu and Alma. I can resize it and it'll stay through multiple vnmrj opens/closes until wsl is shutdown, then it reopens small again. I think it's sizing the window to the splash screen image, because it's hit-or-miss if I see the splash on first load. This happens both when launched from the shortcut or directly from a WSL prompt. The beta3 installer always loaded the window at default size and centered on screen for me, but I've only tested on a single monitor, Windows 10 setup so far.

![image](https://github.com/user-attachments/assets/2b314f97-ed16-4940-9f53-17240ed7899c)

Out of curiosity, if you open the distro you installed with the script, is there anything in /etc/wsl.conf? That should have systemd=true under the [boot] section that would enable systemd to support Locator. If you run ```systemctl status``` does it show as active? And if systemd is active, can you turn the Locator back on without issue?

Also, did you follow the Readme instructions and just close the Admin panel when it opens during install, or did you manually perform any tasks first? It really shouldn't matter, but just wondering if that's why you saw Locator errors. I couldn't reproduce that, though it doesn't really matter now.

The script should have written the shortcuts with the same command that specifies the distribution selected. If you look at the properties of the shortcuts, do you see something like 

> ```C:\Windows\System32\wsl.exe -d Ubuntu-24.04 /bin/bash -lic "vnmrj; sleep 3"``` 

in the Target field?

Currently, it will (or should) overwrite these shortcuts on each distro install. I could make the shortcuts unique to each distro if you thought that would be a good idea. I don't know how many (other) people will be installing multiple versions of OpenVnmrJ though.

**Comment by JessiBaughman** [comment] 2024-09-17 16:16
Well, restarting your computer will have the same effect as wsl --shutdown, which is why I was testing that. 

But it sounds like should someone want to turn the Locator on, it will be fine, so I'm happy with that. I like the idea of dropping those two Ubuntu options, so I'll do that.

Thanks again for testing, feedback, and contributions while being busy with OVJ3.2! I appreciate it.

**Closed by JessiBaughman** 2024-09-17 16:16 UTC
